
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `RoleRate` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model RoleRate
 * 
 */
export type RoleRateModel = runtime.Types.Result.DefaultSelection<Prisma.$RoleRatePayload>

export type AggregateRoleRate = {
  _count: RoleRateCountAggregateOutputType | null
  _avg: RoleRateAvgAggregateOutputType | null
  _sum: RoleRateSumAggregateOutputType | null
  _min: RoleRateMinAggregateOutputType | null
  _max: RoleRateMaxAggregateOutputType | null
}

export type RoleRateAvgAggregateOutputType = {
  monthlyRate: number | null
  baseHours: number | null
  hourlyRate: number | null
}

export type RoleRateSumAggregateOutputType = {
  monthlyRate: number | null
  baseHours: number | null
  hourlyRate: number | null
}

export type RoleRateMinAggregateOutputType = {
  role: string | null
  monthlyRate: number | null
  baseHours: number | null
  hourlyRate: number | null
}

export type RoleRateMaxAggregateOutputType = {
  role: string | null
  monthlyRate: number | null
  baseHours: number | null
  hourlyRate: number | null
}

export type RoleRateCountAggregateOutputType = {
  role: number
  monthlyRate: number
  baseHours: number
  hourlyRate: number
  _all: number
}


export type RoleRateAvgAggregateInputType = {
  monthlyRate?: true
  baseHours?: true
  hourlyRate?: true
}

export type RoleRateSumAggregateInputType = {
  monthlyRate?: true
  baseHours?: true
  hourlyRate?: true
}

export type RoleRateMinAggregateInputType = {
  role?: true
  monthlyRate?: true
  baseHours?: true
  hourlyRate?: true
}

export type RoleRateMaxAggregateInputType = {
  role?: true
  monthlyRate?: true
  baseHours?: true
  hourlyRate?: true
}

export type RoleRateCountAggregateInputType = {
  role?: true
  monthlyRate?: true
  baseHours?: true
  hourlyRate?: true
  _all?: true
}

export type RoleRateAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which RoleRate to aggregate.
   */
  where?: Prisma.RoleRateWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of RoleRates to fetch.
   */
  orderBy?: Prisma.RoleRateOrderByWithRelationInput | Prisma.RoleRateOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.RoleRateWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` RoleRates from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` RoleRates.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned RoleRates
  **/
  _count?: true | RoleRateCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: RoleRateAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: RoleRateSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: RoleRateMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: RoleRateMaxAggregateInputType
}

export type GetRoleRateAggregateType<T extends RoleRateAggregateArgs> = {
      [P in keyof T & keyof AggregateRoleRate]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateRoleRate[P]>
    : Prisma.GetScalarType<T[P], AggregateRoleRate[P]>
}




export type RoleRateGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.RoleRateWhereInput
  orderBy?: Prisma.RoleRateOrderByWithAggregationInput | Prisma.RoleRateOrderByWithAggregationInput[]
  by: Prisma.RoleRateScalarFieldEnum[] | Prisma.RoleRateScalarFieldEnum
  having?: Prisma.RoleRateScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: RoleRateCountAggregateInputType | true
  _avg?: RoleRateAvgAggregateInputType
  _sum?: RoleRateSumAggregateInputType
  _min?: RoleRateMinAggregateInputType
  _max?: RoleRateMaxAggregateInputType
}

export type RoleRateGroupByOutputType = {
  role: string
  monthlyRate: number
  baseHours: number
  hourlyRate: number
  _count: RoleRateCountAggregateOutputType | null
  _avg: RoleRateAvgAggregateOutputType | null
  _sum: RoleRateSumAggregateOutputType | null
  _min: RoleRateMinAggregateOutputType | null
  _max: RoleRateMaxAggregateOutputType | null
}

type GetRoleRateGroupByPayload<T extends RoleRateGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<RoleRateGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof RoleRateGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], RoleRateGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], RoleRateGroupByOutputType[P]>
      }
    >
  >



export type RoleRateWhereInput = {
  AND?: Prisma.RoleRateWhereInput | Prisma.RoleRateWhereInput[]
  OR?: Prisma.RoleRateWhereInput[]
  NOT?: Prisma.RoleRateWhereInput | Prisma.RoleRateWhereInput[]
  role?: Prisma.StringFilter<"RoleRate"> | string
  monthlyRate?: Prisma.FloatFilter<"RoleRate"> | number
  baseHours?: Prisma.IntFilter<"RoleRate"> | number
  hourlyRate?: Prisma.FloatFilter<"RoleRate"> | number
}

export type RoleRateOrderByWithRelationInput = {
  role?: Prisma.SortOrder
  monthlyRate?: Prisma.SortOrder
  baseHours?: Prisma.SortOrder
  hourlyRate?: Prisma.SortOrder
}

export type RoleRateWhereUniqueInput = Prisma.AtLeast<{
  role?: string
  AND?: Prisma.RoleRateWhereInput | Prisma.RoleRateWhereInput[]
  OR?: Prisma.RoleRateWhereInput[]
  NOT?: Prisma.RoleRateWhereInput | Prisma.RoleRateWhereInput[]
  monthlyRate?: Prisma.FloatFilter<"RoleRate"> | number
  baseHours?: Prisma.IntFilter<"RoleRate"> | number
  hourlyRate?: Prisma.FloatFilter<"RoleRate"> | number
}, "role">

export type RoleRateOrderByWithAggregationInput = {
  role?: Prisma.SortOrder
  monthlyRate?: Prisma.SortOrder
  baseHours?: Prisma.SortOrder
  hourlyRate?: Prisma.SortOrder
  _count?: Prisma.RoleRateCountOrderByAggregateInput
  _avg?: Prisma.RoleRateAvgOrderByAggregateInput
  _max?: Prisma.RoleRateMaxOrderByAggregateInput
  _min?: Prisma.RoleRateMinOrderByAggregateInput
  _sum?: Prisma.RoleRateSumOrderByAggregateInput
}

export type RoleRateScalarWhereWithAggregatesInput = {
  AND?: Prisma.RoleRateScalarWhereWithAggregatesInput | Prisma.RoleRateScalarWhereWithAggregatesInput[]
  OR?: Prisma.RoleRateScalarWhereWithAggregatesInput[]
  NOT?: Prisma.RoleRateScalarWhereWithAggregatesInput | Prisma.RoleRateScalarWhereWithAggregatesInput[]
  role?: Prisma.StringWithAggregatesFilter<"RoleRate"> | string
  monthlyRate?: Prisma.FloatWithAggregatesFilter<"RoleRate"> | number
  baseHours?: Prisma.IntWithAggregatesFilter<"RoleRate"> | number
  hourlyRate?: Prisma.FloatWithAggregatesFilter<"RoleRate"> | number
}

export type RoleRateCreateInput = {
  role: string
  monthlyRate: number
  baseHours?: number
  hourlyRate: number
}

export type RoleRateUncheckedCreateInput = {
  role: string
  monthlyRate: number
  baseHours?: number
  hourlyRate: number
}

export type RoleRateUpdateInput = {
  role?: Prisma.StringFieldUpdateOperationsInput | string
  monthlyRate?: Prisma.FloatFieldUpdateOperationsInput | number
  baseHours?: Prisma.IntFieldUpdateOperationsInput | number
  hourlyRate?: Prisma.FloatFieldUpdateOperationsInput | number
}

export type RoleRateUncheckedUpdateInput = {
  role?: Prisma.StringFieldUpdateOperationsInput | string
  monthlyRate?: Prisma.FloatFieldUpdateOperationsInput | number
  baseHours?: Prisma.IntFieldUpdateOperationsInput | number
  hourlyRate?: Prisma.FloatFieldUpdateOperationsInput | number
}

export type RoleRateCreateManyInput = {
  role: string
  monthlyRate: number
  baseHours?: number
  hourlyRate: number
}

export type RoleRateUpdateManyMutationInput = {
  role?: Prisma.StringFieldUpdateOperationsInput | string
  monthlyRate?: Prisma.FloatFieldUpdateOperationsInput | number
  baseHours?: Prisma.IntFieldUpdateOperationsInput | number
  hourlyRate?: Prisma.FloatFieldUpdateOperationsInput | number
}

export type RoleRateUncheckedUpdateManyInput = {
  role?: Prisma.StringFieldUpdateOperationsInput | string
  monthlyRate?: Prisma.FloatFieldUpdateOperationsInput | number
  baseHours?: Prisma.IntFieldUpdateOperationsInput | number
  hourlyRate?: Prisma.FloatFieldUpdateOperationsInput | number
}

export type RoleRateCountOrderByAggregateInput = {
  role?: Prisma.SortOrder
  monthlyRate?: Prisma.SortOrder
  baseHours?: Prisma.SortOrder
  hourlyRate?: Prisma.SortOrder
}

export type RoleRateAvgOrderByAggregateInput = {
  monthlyRate?: Prisma.SortOrder
  baseHours?: Prisma.SortOrder
  hourlyRate?: Prisma.SortOrder
}

export type RoleRateMaxOrderByAggregateInput = {
  role?: Prisma.SortOrder
  monthlyRate?: Prisma.SortOrder
  baseHours?: Prisma.SortOrder
  hourlyRate?: Prisma.SortOrder
}

export type RoleRateMinOrderByAggregateInput = {
  role?: Prisma.SortOrder
  monthlyRate?: Prisma.SortOrder
  baseHours?: Prisma.SortOrder
  hourlyRate?: Prisma.SortOrder
}

export type RoleRateSumOrderByAggregateInput = {
  monthlyRate?: Prisma.SortOrder
  baseHours?: Prisma.SortOrder
  hourlyRate?: Prisma.SortOrder
}

export type StringFieldUpdateOperationsInput = {
  set?: string
}

export type FloatFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type IntFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}



export type RoleRateSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  role?: boolean
  monthlyRate?: boolean
  baseHours?: boolean
  hourlyRate?: boolean
}, ExtArgs["result"]["roleRate"]>

export type RoleRateSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  role?: boolean
  monthlyRate?: boolean
  baseHours?: boolean
  hourlyRate?: boolean
}, ExtArgs["result"]["roleRate"]>

export type RoleRateSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  role?: boolean
  monthlyRate?: boolean
  baseHours?: boolean
  hourlyRate?: boolean
}, ExtArgs["result"]["roleRate"]>

export type RoleRateSelectScalar = {
  role?: boolean
  monthlyRate?: boolean
  baseHours?: boolean
  hourlyRate?: boolean
}

export type RoleRateOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"role" | "monthlyRate" | "baseHours" | "hourlyRate", ExtArgs["result"]["roleRate"]>

export type $RoleRatePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "RoleRate"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    role: string
    monthlyRate: number
    baseHours: number
    hourlyRate: number
  }, ExtArgs["result"]["roleRate"]>
  composites: {}
}

export type RoleRateGetPayload<S extends boolean | null | undefined | RoleRateDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$RoleRatePayload, S>

export type RoleRateCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<RoleRateFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: RoleRateCountAggregateInputType | true
  }

export interface RoleRateDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['RoleRate'], meta: { name: 'RoleRate' } }
  /**
   * Find zero or one RoleRate that matches the filter.
   * @param {RoleRateFindUniqueArgs} args - Arguments to find a RoleRate
   * @example
   * // Get one RoleRate
   * const roleRate = await prisma.roleRate.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends RoleRateFindUniqueArgs>(args: Prisma.SelectSubset<T, RoleRateFindUniqueArgs<ExtArgs>>): Prisma.Prisma__RoleRateClient<runtime.Types.Result.GetResult<Prisma.$RoleRatePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one RoleRate that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {RoleRateFindUniqueOrThrowArgs} args - Arguments to find a RoleRate
   * @example
   * // Get one RoleRate
   * const roleRate = await prisma.roleRate.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends RoleRateFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, RoleRateFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__RoleRateClient<runtime.Types.Result.GetResult<Prisma.$RoleRatePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first RoleRate that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RoleRateFindFirstArgs} args - Arguments to find a RoleRate
   * @example
   * // Get one RoleRate
   * const roleRate = await prisma.roleRate.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends RoleRateFindFirstArgs>(args?: Prisma.SelectSubset<T, RoleRateFindFirstArgs<ExtArgs>>): Prisma.Prisma__RoleRateClient<runtime.Types.Result.GetResult<Prisma.$RoleRatePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first RoleRate that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RoleRateFindFirstOrThrowArgs} args - Arguments to find a RoleRate
   * @example
   * // Get one RoleRate
   * const roleRate = await prisma.roleRate.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends RoleRateFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, RoleRateFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__RoleRateClient<runtime.Types.Result.GetResult<Prisma.$RoleRatePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more RoleRates that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RoleRateFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all RoleRates
   * const roleRates = await prisma.roleRate.findMany()
   * 
   * // Get first 10 RoleRates
   * const roleRates = await prisma.roleRate.findMany({ take: 10 })
   * 
   * // Only select the `role`
   * const roleRateWithRoleOnly = await prisma.roleRate.findMany({ select: { role: true } })
   * 
   */
  findMany<T extends RoleRateFindManyArgs>(args?: Prisma.SelectSubset<T, RoleRateFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$RoleRatePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a RoleRate.
   * @param {RoleRateCreateArgs} args - Arguments to create a RoleRate.
   * @example
   * // Create one RoleRate
   * const RoleRate = await prisma.roleRate.create({
   *   data: {
   *     // ... data to create a RoleRate
   *   }
   * })
   * 
   */
  create<T extends RoleRateCreateArgs>(args: Prisma.SelectSubset<T, RoleRateCreateArgs<ExtArgs>>): Prisma.Prisma__RoleRateClient<runtime.Types.Result.GetResult<Prisma.$RoleRatePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many RoleRates.
   * @param {RoleRateCreateManyArgs} args - Arguments to create many RoleRates.
   * @example
   * // Create many RoleRates
   * const roleRate = await prisma.roleRate.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends RoleRateCreateManyArgs>(args?: Prisma.SelectSubset<T, RoleRateCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many RoleRates and returns the data saved in the database.
   * @param {RoleRateCreateManyAndReturnArgs} args - Arguments to create many RoleRates.
   * @example
   * // Create many RoleRates
   * const roleRate = await prisma.roleRate.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many RoleRates and only return the `role`
   * const roleRateWithRoleOnly = await prisma.roleRate.createManyAndReturn({
   *   select: { role: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends RoleRateCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, RoleRateCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$RoleRatePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a RoleRate.
   * @param {RoleRateDeleteArgs} args - Arguments to delete one RoleRate.
   * @example
   * // Delete one RoleRate
   * const RoleRate = await prisma.roleRate.delete({
   *   where: {
   *     // ... filter to delete one RoleRate
   *   }
   * })
   * 
   */
  delete<T extends RoleRateDeleteArgs>(args: Prisma.SelectSubset<T, RoleRateDeleteArgs<ExtArgs>>): Prisma.Prisma__RoleRateClient<runtime.Types.Result.GetResult<Prisma.$RoleRatePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one RoleRate.
   * @param {RoleRateUpdateArgs} args - Arguments to update one RoleRate.
   * @example
   * // Update one RoleRate
   * const roleRate = await prisma.roleRate.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends RoleRateUpdateArgs>(args: Prisma.SelectSubset<T, RoleRateUpdateArgs<ExtArgs>>): Prisma.Prisma__RoleRateClient<runtime.Types.Result.GetResult<Prisma.$RoleRatePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more RoleRates.
   * @param {RoleRateDeleteManyArgs} args - Arguments to filter RoleRates to delete.
   * @example
   * // Delete a few RoleRates
   * const { count } = await prisma.roleRate.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends RoleRateDeleteManyArgs>(args?: Prisma.SelectSubset<T, RoleRateDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more RoleRates.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RoleRateUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many RoleRates
   * const roleRate = await prisma.roleRate.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends RoleRateUpdateManyArgs>(args: Prisma.SelectSubset<T, RoleRateUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more RoleRates and returns the data updated in the database.
   * @param {RoleRateUpdateManyAndReturnArgs} args - Arguments to update many RoleRates.
   * @example
   * // Update many RoleRates
   * const roleRate = await prisma.roleRate.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more RoleRates and only return the `role`
   * const roleRateWithRoleOnly = await prisma.roleRate.updateManyAndReturn({
   *   select: { role: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends RoleRateUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, RoleRateUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$RoleRatePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one RoleRate.
   * @param {RoleRateUpsertArgs} args - Arguments to update or create a RoleRate.
   * @example
   * // Update or create a RoleRate
   * const roleRate = await prisma.roleRate.upsert({
   *   create: {
   *     // ... data to create a RoleRate
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the RoleRate we want to update
   *   }
   * })
   */
  upsert<T extends RoleRateUpsertArgs>(args: Prisma.SelectSubset<T, RoleRateUpsertArgs<ExtArgs>>): Prisma.Prisma__RoleRateClient<runtime.Types.Result.GetResult<Prisma.$RoleRatePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of RoleRates.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RoleRateCountArgs} args - Arguments to filter RoleRates to count.
   * @example
   * // Count the number of RoleRates
   * const count = await prisma.roleRate.count({
   *   where: {
   *     // ... the filter for the RoleRates we want to count
   *   }
   * })
  **/
  count<T extends RoleRateCountArgs>(
    args?: Prisma.Subset<T, RoleRateCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], RoleRateCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a RoleRate.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RoleRateAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends RoleRateAggregateArgs>(args: Prisma.Subset<T, RoleRateAggregateArgs>): Prisma.PrismaPromise<GetRoleRateAggregateType<T>>

  /**
   * Group by RoleRate.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RoleRateGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends RoleRateGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: RoleRateGroupByArgs['orderBy'] }
      : { orderBy?: RoleRateGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, RoleRateGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetRoleRateGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the RoleRate model
 */
readonly fields: RoleRateFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for RoleRate.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__RoleRateClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the RoleRate model
 */
export interface RoleRateFieldRefs {
  readonly role: Prisma.FieldRef<"RoleRate", 'String'>
  readonly monthlyRate: Prisma.FieldRef<"RoleRate", 'Float'>
  readonly baseHours: Prisma.FieldRef<"RoleRate", 'Int'>
  readonly hourlyRate: Prisma.FieldRef<"RoleRate", 'Float'>
}
    

// Custom InputTypes
/**
 * RoleRate findUnique
 */
export type RoleRateFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RoleRate
   */
  select?: Prisma.RoleRateSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RoleRate
   */
  omit?: Prisma.RoleRateOmit<ExtArgs> | null
  /**
   * Filter, which RoleRate to fetch.
   */
  where: Prisma.RoleRateWhereUniqueInput
}

/**
 * RoleRate findUniqueOrThrow
 */
export type RoleRateFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RoleRate
   */
  select?: Prisma.RoleRateSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RoleRate
   */
  omit?: Prisma.RoleRateOmit<ExtArgs> | null
  /**
   * Filter, which RoleRate to fetch.
   */
  where: Prisma.RoleRateWhereUniqueInput
}

/**
 * RoleRate findFirst
 */
export type RoleRateFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RoleRate
   */
  select?: Prisma.RoleRateSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RoleRate
   */
  omit?: Prisma.RoleRateOmit<ExtArgs> | null
  /**
   * Filter, which RoleRate to fetch.
   */
  where?: Prisma.RoleRateWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of RoleRates to fetch.
   */
  orderBy?: Prisma.RoleRateOrderByWithRelationInput | Prisma.RoleRateOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for RoleRates.
   */
  cursor?: Prisma.RoleRateWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` RoleRates from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` RoleRates.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of RoleRates.
   */
  distinct?: Prisma.RoleRateScalarFieldEnum | Prisma.RoleRateScalarFieldEnum[]
}

/**
 * RoleRate findFirstOrThrow
 */
export type RoleRateFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RoleRate
   */
  select?: Prisma.RoleRateSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RoleRate
   */
  omit?: Prisma.RoleRateOmit<ExtArgs> | null
  /**
   * Filter, which RoleRate to fetch.
   */
  where?: Prisma.RoleRateWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of RoleRates to fetch.
   */
  orderBy?: Prisma.RoleRateOrderByWithRelationInput | Prisma.RoleRateOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for RoleRates.
   */
  cursor?: Prisma.RoleRateWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` RoleRates from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` RoleRates.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of RoleRates.
   */
  distinct?: Prisma.RoleRateScalarFieldEnum | Prisma.RoleRateScalarFieldEnum[]
}

/**
 * RoleRate findMany
 */
export type RoleRateFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RoleRate
   */
  select?: Prisma.RoleRateSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RoleRate
   */
  omit?: Prisma.RoleRateOmit<ExtArgs> | null
  /**
   * Filter, which RoleRates to fetch.
   */
  where?: Prisma.RoleRateWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of RoleRates to fetch.
   */
  orderBy?: Prisma.RoleRateOrderByWithRelationInput | Prisma.RoleRateOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing RoleRates.
   */
  cursor?: Prisma.RoleRateWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` RoleRates from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` RoleRates.
   */
  skip?: number
  distinct?: Prisma.RoleRateScalarFieldEnum | Prisma.RoleRateScalarFieldEnum[]
}

/**
 * RoleRate create
 */
export type RoleRateCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RoleRate
   */
  select?: Prisma.RoleRateSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RoleRate
   */
  omit?: Prisma.RoleRateOmit<ExtArgs> | null
  /**
   * The data needed to create a RoleRate.
   */
  data: Prisma.XOR<Prisma.RoleRateCreateInput, Prisma.RoleRateUncheckedCreateInput>
}

/**
 * RoleRate createMany
 */
export type RoleRateCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many RoleRates.
   */
  data: Prisma.RoleRateCreateManyInput | Prisma.RoleRateCreateManyInput[]
}

/**
 * RoleRate createManyAndReturn
 */
export type RoleRateCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RoleRate
   */
  select?: Prisma.RoleRateSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the RoleRate
   */
  omit?: Prisma.RoleRateOmit<ExtArgs> | null
  /**
   * The data used to create many RoleRates.
   */
  data: Prisma.RoleRateCreateManyInput | Prisma.RoleRateCreateManyInput[]
}

/**
 * RoleRate update
 */
export type RoleRateUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RoleRate
   */
  select?: Prisma.RoleRateSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RoleRate
   */
  omit?: Prisma.RoleRateOmit<ExtArgs> | null
  /**
   * The data needed to update a RoleRate.
   */
  data: Prisma.XOR<Prisma.RoleRateUpdateInput, Prisma.RoleRateUncheckedUpdateInput>
  /**
   * Choose, which RoleRate to update.
   */
  where: Prisma.RoleRateWhereUniqueInput
}

/**
 * RoleRate updateMany
 */
export type RoleRateUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update RoleRates.
   */
  data: Prisma.XOR<Prisma.RoleRateUpdateManyMutationInput, Prisma.RoleRateUncheckedUpdateManyInput>
  /**
   * Filter which RoleRates to update
   */
  where?: Prisma.RoleRateWhereInput
  /**
   * Limit how many RoleRates to update.
   */
  limit?: number
}

/**
 * RoleRate updateManyAndReturn
 */
export type RoleRateUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RoleRate
   */
  select?: Prisma.RoleRateSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the RoleRate
   */
  omit?: Prisma.RoleRateOmit<ExtArgs> | null
  /**
   * The data used to update RoleRates.
   */
  data: Prisma.XOR<Prisma.RoleRateUpdateManyMutationInput, Prisma.RoleRateUncheckedUpdateManyInput>
  /**
   * Filter which RoleRates to update
   */
  where?: Prisma.RoleRateWhereInput
  /**
   * Limit how many RoleRates to update.
   */
  limit?: number
}

/**
 * RoleRate upsert
 */
export type RoleRateUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RoleRate
   */
  select?: Prisma.RoleRateSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RoleRate
   */
  omit?: Prisma.RoleRateOmit<ExtArgs> | null
  /**
   * The filter to search for the RoleRate to update in case it exists.
   */
  where: Prisma.RoleRateWhereUniqueInput
  /**
   * In case the RoleRate found by the `where` argument doesn't exist, create a new RoleRate with this data.
   */
  create: Prisma.XOR<Prisma.RoleRateCreateInput, Prisma.RoleRateUncheckedCreateInput>
  /**
   * In case the RoleRate was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.RoleRateUpdateInput, Prisma.RoleRateUncheckedUpdateInput>
}

/**
 * RoleRate delete
 */
export type RoleRateDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RoleRate
   */
  select?: Prisma.RoleRateSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RoleRate
   */
  omit?: Prisma.RoleRateOmit<ExtArgs> | null
  /**
   * Filter which RoleRate to delete.
   */
  where: Prisma.RoleRateWhereUniqueInput
}

/**
 * RoleRate deleteMany
 */
export type RoleRateDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which RoleRates to delete
   */
  where?: Prisma.RoleRateWhereInput
  /**
   * Limit how many RoleRates to delete.
   */
  limit?: number
}

/**
 * RoleRate without action
 */
export type RoleRateDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RoleRate
   */
  select?: Prisma.RoleRateSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RoleRate
   */
  omit?: Prisma.RoleRateOmit<ExtArgs> | null
}
